#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift_defs/exception_types/exception_types_types'
require 'thrift_defs/geo_types/geo_types_types'
require 'thrift_defs/request_types/request_types_types'
require 'thrift_defs/voter_record_types/voter_record_types_types'


module ThriftDefs
  module VoterVerifier
  end
end
