RSpec.shared_examples_for 'autogenerates a UUID' do
  context 'when no UUID is provided' do
    let!(:saved_record) { create(described_class.name.underscore.to_sym) }

    it 'is given an autogenerated UUID' do
      expect(saved_record.uuid).to be_a_uuid
    end
  end

  context 'when a UUID is provided on initialization' do
    let(:uuid) { '00000000-0000-0000-0000-000000000000' }
    let!(:saved_record) { create(described_class.name.underscore.to_sym, uuid: uuid) }

    it 'is not given an autogenerated UUID' do
      expect(saved_record.uuid).to eq(uuid)
    end

    context 'when the record is fetched from the database' do
      it 'does not assign a new UUID' do
        expect(described_class.find(saved_record.id).uuid).to eq(uuid)
      end
    end
  end
end
