#
# Autogenerated by Thrift Compiler (0.12.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift_defs/exception_types/exception_types_types'

module ThriftDefs
  module ExceptionTypes
  end
end
